name: Build [make]
on: [push, pull_request]

jobs:
  build:
    name: Build Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build with make
      working-directory: ./
      run: make

