name: Format [clang-format]
on: [push, pull_request]

jobs:
  format:
    name: Formatting Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1.9.0
      with:
        version: "16.0"

    - name: Run clang-format style check for C programs.
      uses: jidicula/clang-format-action@v4.11.0
      with:
        clang-format-version: '16'
        check-path: 'src'
        fallback-style: 'Chromium'
